### ISSUE TITLE
TODO: update documentations

### ISSUE THREAD

**Issue by aviatesk** [JunoLab/Juno.jl#419]
We have such a beautiful documentation, and it can be even nicer.

Here are several TODOs I'm recognising now:
- Update screenshots in https://junolab.org so that they will reflect our recent UIs and new features:
  * [ ] outline view
  * [ ] completions including local bindings
  * [ ] debugger pane
  * [ ] goto & hyperclick
- explanations for the usage documentation pane -- there are several undocumented tips in that
  * [ ] regenerate documentation cache
  * [ ] add explanations for search options
  * [ ] show module description (README)
- add description for our recent features by static code-analysis
  * [ ] outline view
  * [ ] goto symbols (from editor/docs/workspace)
  * [ ] rename refactor (to be implemented)

Feel free to add anything you want :)
